### PR TITLE
Remove Modal `forcedScroll` prop / Default `overflow` to `auto`

### PR DESCRIPTION
**Pull request by dblandin**
Slack thread: https://artsy.slack.com/archives/C9XJKPY9W/p1576267394001200

This will be a breaking change and will required some compatibility updates in @artsy/reaction.

### Before

Peek 2020-05-13 12-46

### After

Peek 2020-05-13 12-44

### CODE REVIEW

**Comment by damassi** [comment]
@dblandin - Mind sequentially listing exactly what compatability updates are needed to take this to completion in the PR description?

**Comment by dblandin** [comment]
> Mind listing in the PR description exactly what compatibility updates are needed to take this to completion? Then the work required isn't all in yr head and if need be someone else could pick it up.

Sure thing! The main change is to remove all uses of the `forcedScroll` Modal prop.

I'll echo a comment I made in Slack: another option might be to keep the `forcedScroll` property and set it explicitly to true to keep the `overflow: scroll` behavior for existing modals, but I still get the feeling that this is accidental, not intentional, behavior so I'm hesitant to do that.

In that case, we could remove any `forcedScroll={false}` properties, as that will be the new default behavior, and set `forcedScroll={true}` to any existing modals where we're unsure of whether it's needed or not.

@damassi Do you have any preference here?

**Comment by damassi** [comment]
Nope, no preference! `forcedScroll` seems weird to me, and not sure why it was ever needed.

**Comment by dblandin** [comment]
> Nope, no preference! forcedScroll seems weird to me, and not sure why it was ever needed.

I think this `overflow: scroll` setting has always been confusing and the `forcedScroll` property was introduced to get around it temporarily: https://github.com/artsy/palette/pull/623

**Comment by dblandin** [comment]
Going to go ahead and merge this in.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v9.0.0`](https://github.com/artsy/palette/releases/tag/v9.0.0) :rocket:

**Pull request merged**
