### PR TITLE
Generate stylesheet

### PR DESCRIPTION
**Pull request by zephraph**
In certain situations we may want to use palette styles, but may not yet be positioned to integrate react. In these situations it might be easier to provide a low touch, incremental step of having a stylesheet with most of palette's basic styles. 

This PR adds a `generate-styles` command which (along style `generate-tokens`) gives us more options for consuming palette values outside of the react ecosystem. 

<details>
  <summary>An example output</summary>

```css
:root {
  --space-1: 10px;
  --space-2: 20px;
  --space-3: 30px;
  --space-4: 40px;
  --space-6: 60px;
  --space-9: 90px;
  --space-12: 120px;
  --space-18: 180px;
  --space-0_3: 3px;
  --space-0_5: 5px;
  --color-black100: #000;
  --color-black80: #333;
  --color-black60: #666;
  --color-black30: #c2c2c2;
  --color-black10: #e5e5e5;
  --color-black5: #f8f8f8;
  --color-purple100: #6e1eff;
  --color-purple30: #d3bbff;
  --color-purple5: #f8f3ff;
  --color-green100: #0eda83;
  --color-red100: #f7625a;
  --color-yellow100: #f1af1b;
  --color-yellow30: #fae7ba;
  --color-yellow10: #fdf7e8;
  --color-white100: #fff;
}
.m-1 {
  margin: 10px;
}
.mt-1 {
  margin-top: 10px;
}
.mb-1 {
  margin-bottom: 10px;
}
.ml-1 {
  margin-left: 10px;
}
.mr-1 {
  margin-right: 10px;
}
.mx-1 {
  margin-right: 10px;
  margin-left: 10px;
}
.my-1 {
  margin-top: 10px;
  margin-bottom: 10px;
}
.p-1 {
  padding: 10px;
}
.pt-1 {
  padding-top: 10px;
}
.pb-1 {
  padding-bottom: 10px;
}
.pl-1 {
  padding-left: 10px;
}
.pr-1 {
  padding-right: 10px;
}
.px-1 {
  padding-right: 10px;
  padding-left: 10px;
}
.py-1 {
  padding-top: 10px;
  padding-bottom: 10px;
}
.m-2 {
  margin: 20px;
}
.mt-2 {
  margin-top: 20px;
}
.mb-2 {
  margin-bottom: 20px;
}
.ml-2 {
  margin-left: 20px;
}
.mr-2 {
  margin-right: 20px;
}
.mx-2 {
  margin-right: 20px;
  margin-left: 20px;
}
.my-2 {
  margin-top: 20px;
  margin-bottom: 20px;
}
.p-2 {
  padding: 20px;
}
.pt-2 {
  padding-top: 20px;
}
.pb-2 {
  padding-bottom: 20px;
}
.pl-2 {
  padding-left: 20px;
}
.pr-2 {
  padding-right: 20px;
}
.px-2 {
  padding-right: 20px;
  padding-left: 20px;
}
.py-2 {
  padding-top: 20px;
  padding-bottom: 20px;
}
.m-3 {
  margin: 30px;
}
.mt-3 {
  margin-top: 30px;
}
.mb-3 {
  margin-bottom: 30px;
}
.ml-3 {
  margin-left: 30px;
}
.mr-3 {
  margin-right: 30px;
}
.mx-3 {
  margin-right: 30px;
  margin-left: 30px;
}
.my-3 {
  margin-top: 30px;
  margin-bottom: 30px;
}
.p-3 {
  padding: 30px;
}
.pt-3 {
  padding-top: 30px;
}
.pb-3 {
  padding-bottom: 30px;
}
.pl-3 {
  padding-left: 30px;
}
.pr-3 {
  padding-right: 30px;
}
.px-3 {
  padding-right: 30px;
  padding-left: 30px;
}
.py-3 {
  padding-top: 30px;
  padding-bottom: 30px;
}
.m-4 {
  margin: 40px;
}
.mt-4 {
  margin-top: 40px;
}
.mb-4 {
  margin-bottom: 40px;
}
.ml-4 {
  margin-left: 40px;
}
.mr-4 {
  margin-right: 40px;
}
.mx-4 {
  margin-right: 40px;
  margin-left: 40px;
}
.my-4 {
  margin-top: 40px;
  margin-bottom: 40px;
}
.p-4 {
  padding: 40px;
}
.pt-4 {
  padding-top: 40px;
}
.pb-4 {
  padding-bottom: 40px;
}
.pl-4 {
  padding-left: 40px;
}
.pr-4 {
  padding-right: 40px;
}
.px-4 {
  padding-right: 40px;
  padding-left: 40px;
}
.py-4 {
  padding-top: 40px;
  padding-bottom: 40px;
}
.m-6 {
  margin: 60px;
}
.mt-6 {
  margin-top: 60px;
}
.mb-6 {
  margin-bottom: 60px;
}
.ml-6 {
  margin-left: 60px;
}
.mr-6 {
  margin-right: 60px;
}
.mx-6 {
  margin-right: 60px;
  margin-left: 60px;
}
.my-6 {
  margin-top: 60px;
  margin-bottom: 60px;
}
.p-6 {
  padding: 60px;
}
.pt-6 {
  padding-top: 60px;
}
.pb-6 {
  padding-bottom: 60px;
}
.pl-6 {
  padding-left: 60px;
}
.pr-6 {
  padding-right: 60px;
}
.px-6 {
  padding-right: 60px;
  padding-left: 60px;
}
.py-6 {
  padding-top: 60px;
  padding-bottom: 60px;
}
.m-9 {
  margin: 90px;
}
.mt-9 {
  margin-top: 90px;
}
.mb-9 {
  margin-bottom: 90px;
}
.ml-9 {
  margin-left: 90px;
}
.mr-9 {
  margin-right: 90px;
}
.mx-9 {
  margin-right: 90px;
  margin-left: 90px;
}
.my-9 {
  margin-top: 90px;
  margin-bottom: 90px;
}
.p-9 {
  padding: 90px;
}
.pt-9 {
  padding-top: 90px;
}
.pb-9 {
  padding-bottom: 90px;
}
.pl-9 {
  padding-left: 90px;
}
.pr-9 {
  padding-right: 90px;
}
.px-9 {
  padding-right: 90px;
  padding-left: 90px;
}
.py-9 {
  padding-top: 90px;
  padding-bottom: 90px;
}
.m-12 {
  margin: 120px;
}
.mt-12 {
  margin-top: 120px;
}
.mb-12 {
  margin-bottom: 120px;
}
.ml-12 {
  margin-left: 120px;
}
.mr-12 {
  margin-right: 120px;
}
.mx-12 {
  margin-right: 120px;
  margin-left: 120px;
}
.my-12 {
  margin-top: 120px;
  margin-bottom: 120px;
}
.p-12 {
  padding: 120px;
}
.pt-12 {
  padding-top: 120px;
}
.pb-12 {
  padding-bottom: 120px;
}
.pl-12 {
  padding-left: 120px;
}
.pr-12 {
  padding-right: 120px;
}
.px-12 {
  padding-right: 120px;
  padding-left: 120px;
}
.py-12 {
  padding-top: 120px;
  padding-bottom: 120px;
}
.m-18 {
  margin: 180px;
}
.mt-18 {
  margin-top: 180px;
}
.mb-18 {
  margin-bottom: 180px;
}
.ml-18 {
  margin-left: 180px;
}
.mr-18 {
  margin-right: 180px;
}
.mx-18 {
  margin-right: 180px;
  margin-left: 180px;
}
.my-18 {
  margin-top: 180px;
  margin-bottom: 180px;
}
.p-18 {
  padding: 180px;
}
.pt-18 {
  padding-top: 180px;
}
.pb-18 {
  padding-bottom: 180px;
}
.pl-18 {
  padding-left: 180px;
}
.pr-18 {
  padding-right: 180px;
}
.px-18 {
  padding-right: 180px;
  padding-left: 180px;
}
.py-18 {
  padding-top: 180px;
  padding-bottom: 180px;
}
.m-0_3 {
  margin: 3px;
}
.mt-0_3 {
  margin-top: 3px;
}
.mb-0_3 {
  margin-bottom: 3px;
}
.ml-0_3 {
  margin-left: 3px;
}
.mr-0_3 {
  margin-right: 3px;
}
.mx-0_3 {
  margin-right: 3px;
  margin-left: 3px;
}
.my-0_3 {
  margin-top: 3px;
  margin-bottom: 3px;
}
.p-0_3 {
  padding: 3px;
}
.pt-0_3 {
  padding-top: 3px;
}
.pb-0_3 {
  padding-bottom: 3px;
}
.pl-0_3 {
  padding-left: 3px;
}
.pr-0_3 {
  padding-right: 3px;
}
.px-0_3 {
  padding-right: 3px;
  padding-left: 3px;
}
.py-0_3 {
  padding-top: 3px;
  padding-bottom: 3px;
}
.m-0_5 {
  margin: 5px;
}
.mt-0_5 {
  margin-top: 5px;
}
.mb-0_5 {
  margin-bottom: 5px;
}
.ml-0_5 {
  margin-left: 5px;
}
.mr-0_5 {
  margin-right: 5px;
}
.mx-0_5 {
  margin-right: 5px;
  margin-left: 5px;
}
.my-0_5 {
  margin-top: 5px;
  margin-bottom: 5px;
}
.p-0_5 {
  padding: 5px;
}
.pt-0_5 {
  padding-top: 5px;
}
.pb-0_5 {
  padding-bottom: 5px;
}
.pl-0_5 {
  padding-left: 5px;
}
.pr-0_5 {
  padding-right: 5px;
}
.px-0_5 {
  padding-right: 5px;
  padding-left: 5px;
}
.py-0_5 {
  padding-top: 5px;
  padding-bottom: 5px;
}
.color-black100 {
  color: #000;
}
.bg-color-black100 {
  background: #000;
}

.color-black80 {
  color: #333;
}
.bg-color-black80 {
  background: #333;
}

.color-black60 {
  color: #666;
}
.bg-color-black60 {
  background: #666;
}

.color-black30 {
  color: #c2c2c2;
}
.bg-color-black30 {
  background: #c2c2c2;
}

.color-black10 {
  color: #e5e5e5;
}
.bg-color-black10 {
  background: #e5e5e5;
}

.color-black5 {
  color: #f8f8f8;
}
.bg-color-black5 {
  background: #f8f8f8;
}

.color-purple100 {
  color: #6e1eff;
}
.bg-color-purple100 {
  background: #6e1eff;
}

.color-purple30 {
  color: #d3bbff;
}
.bg-color-purple30 {
  background: #d3bbff;
}

.color-purple5 {
  color: #f8f3ff;
}
.bg-color-purple5 {
  background: #f8f3ff;
}

.color-green100 {
  color: #0eda83;
}
.bg-color-green100 {
  background: #0eda83;
}

.color-red100 {
  color: #f7625a;
}
.bg-color-red100 {
  background: #f7625a;
}

.color-yellow100 {
  color: #f1af1b;
}
.bg-color-yellow100 {
  background: #f1af1b;
}

.color-yellow30 {
  color: #fae7ba;
}
.bg-color-yellow30 {
  background: #fae7ba;
}

.color-yellow10 {
  color: #fdf7e8;
}
.bg-color-yellow10 {
  background: #fdf7e8;
}

.color-white100 {
  color: #fff;
}
.bg-color-white100 {
  background: #fff;
}

.sans-0 {
  font: 8px/8px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-1 {
  font: 10px/14px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-2 {
  font: 12px/16px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3 {
  font: 14px/24px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4 {
  font: 16px/26px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5 {
  font: 18px/30px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-6 {
  font: 22px/30px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-8 {
  font: 28px/36px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-10 {
  font: 42px/50px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-12 {
  font: 60px/66px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-14 {
  font: 80px/84px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-16 {
  font: 100px/104px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3t {
  font: 14px/20px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4t {
  font: 16px/22px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5t {
  font: 18px/26px Unica77LLWebRegular, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-0-italic {
  font: italic 8px/8px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-1-italic {
  font: italic 10px/14px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-2-italic {
  font: italic 12px/16px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3-italic {
  font: italic 14px/24px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4-italic {
  font: italic 16px/26px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5-italic {
  font: italic 18px/30px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-6-italic {
  font: italic 22px/30px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-8-italic {
  font: italic 28px/36px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-10-italic {
  font: italic 42px/50px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-12-italic {
  font: italic 60px/66px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-14-italic {
  font: italic 80px/84px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-16-italic {
  font: italic 100px/104px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3t-italic {
  font: italic 14px/20px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4t-italic {
  font: italic 16px/22px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5t-italic {
  font: italic 18px/26px Unica77LLWebItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-0-medium {
  font: 500 8px/8px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-1-medium {
  font: 500 10px/14px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-2-medium {
  font: 500 12px/16px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3-medium {
  font: 500 14px/24px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4-medium {
  font: 500 16px/26px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5-medium {
  font: 500 18px/30px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-6-medium {
  font: 500 22px/30px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-8-medium {
  font: 500 28px/36px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-10-medium {
  font: 500 42px/50px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-12-medium {
  font: 500 60px/66px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-14-medium {
  font: 500 80px/84px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-16-medium {
  font: 500 100px/104px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3t-medium {
  font: 500 14px/20px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4t-medium {
  font: 500 16px/22px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5t-medium {
  font: 500 18px/26px Unica77LLWebMedium, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-0-medium-italic {
  font: italic 500 8px/8px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-1-medium-italic {
  font: italic 500 10px/14px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-2-medium-italic {
  font: italic 500 12px/16px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3-medium-italic {
  font: italic 500 14px/24px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4-medium-italic {
  font: italic 500 16px/26px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5-medium-italic {
  font: italic 500 18px/30px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-6-medium-italic {
  font: italic 500 22px/30px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-8-medium-italic {
  font: italic 500 28px/36px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-10-medium-italic {
  font: italic 500 42px/50px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-12-medium-italic {
  font: italic 500 60px/66px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-14-medium-italic {
  font: italic 500 80px/84px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-16-medium-italic {
  font: italic 500 100px/104px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-3t-medium-italic {
  font: italic 500 14px/20px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-4t-medium-italic {
  font: italic 500 16px/22px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.sans-5t-medium-italic {
  font: italic 500 18px/26px Unica77LLWebMediumItalic, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.serif-1 {
  font: 12px/16px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-2 {
  font: 14px/18px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-3 {
  font: 16px/24px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-4 {
  font: 18px/26px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-5 {
  font: 22px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-6 {
  font: 26px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-8 {
  font: 32px/38px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-10 {
  font: 44px/50px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-12 {
  font: 60px/70px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-3t {
  font: 16px/20px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-4t {
  font: 18px/22px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-5t {
  font: 22px/28px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times, serif;
}

.serif-1-italic {
  font: italic 12px/16px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-2-italic {
  font: italic 14px/18px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-3-italic {
  font: italic 16px/24px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-4-italic {
  font: italic 18px/26px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-5-italic {
  font: italic 22px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-6-italic {
  font: italic 26px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-8-italic {
  font: italic 32px/38px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-10-italic {
  font: italic 44px/50px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-12-italic {
  font: italic 60px/70px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-3t-italic {
  font: italic 16px/20px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-4t-italic {
  font: italic 18px/22px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-5t-italic {
  font: italic 22px/28px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-1-semibold {
  font: 600 12px/16px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-2-semibold {
  font: 600 14px/18px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-3-semibold {
  font: 600 16px/24px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-4-semibold {
  font: 600 18px/26px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-5-semibold {
  font: 600 22px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-6-semibold {
  font: 600 26px/32px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-8-semibold {
  font: 600 32px/38px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-10-semibold {
  font: 600 44px/50px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-12-semibold {
  font: 600 60px/70px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-3t-semibold {
  font: 600 16px/20px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-4t-semibold {
  font: 600 18px/22px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.serif-5t-semibold {
  font: 600 22px/28px "Adobe Garamond W08", "adobe-garamond-pro", "AGaramondPro-Regular", "Times New Roman", Times,
    serif;
}

.display-2 {
  font: 10px/12px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}

.display-6 {
  font: 18px/22px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}

.display-8 {
  font: 22px/24px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}

.display-3t {
  font: 12px/16px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}

.display-4t {
  font: 14px/18px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}

.display-5t {
  font: 16px/20px "ITC Avant Garde Gothic W04", "AvantGardeGothicITCW01D 731075", AvantGardeGothicITCW01Dm, Helvetica,
    sans-serif;
}
```

</details>

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit e0a87412a99a05e0c0a88d8cf008797b6c28637f

https://deploy-preview-376--artsy-palette.netlify.com

**Comment by zephraph** [comment]
>Nice!! 🙌 with this, the plan is to still install `artsy/palette` but now be able to use outside of react, right?

@ashkan18 yep, that's the idea. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zephraph** [comment]
@jonallured I'm 👍 on those changes. As for the build artifact, I thought about that. I was looking into doing something custom at first, but we can just use [unpkg](https://unpkg.com) to pull the files we need down. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artsyit** [comment]
:rocket: PR was released in v4.9.0 :rocket:

**Pull request merged**
