### PR TITLE
Remove test files from published package

### PR DESCRIPTION
**Pull request by ds300**
Was doing some personal open source stuff and noticed that we're publishing a lot of test files in palette. This removes them just before the package is created.

Here's the full list of files that are deleted by this PR:

```
dist/elements/Avatar/Avatar.test.d.ts
dist/elements/Avatar/Avatar.test.js
dist/elements/Avatar/Avatar.test.js.map
dist/elements/Banner/Banner.test.d.ts
dist/elements/Banner/Banner.test.js
dist/elements/Banner/Banner.test.js.map
dist/elements/BarChart/BarChart.test.d.ts
dist/elements/BarChart/BarChart.test.js
dist/elements/BarChart/BarChart.test.js.map
dist/elements/Button/Button.test.d.ts
dist/elements/Button/Button.test.js
dist/elements/Button/Button.test.js.map
dist/elements/Collapse/Collapse.test.d.ts
dist/elements/Collapse/Collapse.test.js
dist/elements/Collapse/Collapse.test.js.map
dist/elements/Input/Input.test.d.ts
dist/elements/Input/Input.test.js
dist/elements/Input/Input.test.js.map
dist/elements/Join/Join.test.d.ts
dist/elements/Join/Join.test.js
dist/elements/Join/Join.test.js.map
dist/elements/Pagination/__tests__/Pagination.test.d.ts
dist/elements/RadioGroup/RadioGroup.test.d.ts
dist/elements/RadioGroup/RadioGroup.test.js
dist/elements/RadioGroup/RadioGroup.test.js.map
dist/elements/ReadMore/__tests__/ReadMore.test.d.ts
dist/elements/Select/Select.test.d.ts
dist/elements/Select/Select.test.js
dist/elements/Select/Select.test.js.map
dist/elements/Stepper/__tests__/Stepper.test.d.ts
dist/elements/Tabs/__tests__/Tabs.test.d.ts
dist/elements/Tag/__tests__/Tag.test.d.ts
dist/elements/TextArea/__tests__/TextArea.test.d.ts
dist/elements/Toggle/__tests__/Toggle.test.d.ts
dist/elements/Typography/Typography.test.d.ts
dist/elements/Typography/Typography.test.js
dist/elements/Typography/Typography.test.js.map
dist/elements/Typography/determineFontSizes.test.d.ts
dist/elements/Typography/determineFontSizes.test.js
dist/elements/Typography/determineFontSizes.test.js.map
dist/helpers/__tests__/color.test.d.ts
dist/helpers/__tests__/media.test.d.ts
dist/helpers/__tests__/space.test.d.ts
dist/__tests__
dist/elements/Pagination/__tests__
dist/elements/ReadMore/__tests__
dist/elements/Stepper/__tests__
dist/elements/Tabs/__tests__
dist/elements/Tag/__tests__
dist/elements/TextArea/__tests__
dist/elements/Toggle/__tests__
dist/helpers/__tests__
```

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit b1381093458c1f59d3d563a23fd6e303aaf1692f

https://deploy-preview-371--artsy-palette.netlify.com

**Comment by zephraph** [comment]
Shouldn’t we just use an .npmignore? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zephraph** [comment]
Check out reaction’s: https://github.com/artsy/reaction/blob/master/.npmignore

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ds300** [comment]
YES THAT IS MUCH MORE SENSIBLE  ❤️ 

I'm gonna steal it for patch-package.

**Comment by zephraph** [comment]
Also, you can use `npm publish —dry-run` to get a preview of which files will be published (when you need to fine tune things). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by damassi** [comment]
👍

**Comment by artsyit** [comment]
:rocket: PR was released in v4.7.2 :rocket:

**Pull request merged**
