### PR TITLE
[Lib] Bump styled-components 4.0.3

### PR DESCRIPTION
**Pull request by damassi**
This locks styled-components at 4.0.3 based on [this suggestion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30536).

Part of a coordinated merge across Reaction and Force. 

- https://github.com/artsy/reaction/pull/1870
- https://github.com/artsy/force/pull/3339

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit c432d6b4db4303b82bcc6d8732ff503ed1b42881

https://deploy-preview-180--artsy-palette.netlify.com

**Comment by damassi** [comment]
@zephraph - better now than never, this is ready go. Conflicts are getting intense in reaction.

**Comment by zephraph** [comment]
@damassi the emission update is technically blocked by the RN update that @alloy is working on, right? We'll also need to make sure positron can be upgraded. 

I'm assuming that's all stuff we can get to. If we're okay to hold off on bumping palette version in emission until the RN update then I'm 👍 on this. Thanks for pushing it forward.

**Comment by alloy** [comment]
> If we're okay to hold off on bumping palette version in emission until the RN update then I'm 👍 on this.

cc @l2succes @ashfurrow

**Comment by ashfurrow** [comment]
Makes sense 👍 Just something to be aware of post-RN upgrade. I don't think LD will be blocked by waiting. The changes in the Force/Reaction PRs make sense. Thanks for taking this on, Chris 🚀

**Comment by artsyit** [comment]
:rocket: PR was released in v3.0.0 :rocket:

**Pull request merged**
