### PR TITLE
Final modal spacing fixes

### PR DESCRIPTION
**Pull request by ds300**
Catching up with the spec: https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5c75ad115c1db5628cc03c2a

Just making the padding 20px on mobile and doing some conditional formatting around the logo/title.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 65e5ba689cdf2b29666df01bc5644fcfecb133ff

https://deploy-preview-588--artsy-palette.netlify.com

**Comment by zephraph** [comment]
Good eye!

**Comment by kierangillen** [comment]
Thanks for suggesting these changes, definitely an improvement!

**Comment by artsyit** [comment]
:rocket: PR was released in v4.17.5 :rocket:

**Pull request merged**
