### PR TITLE
feat(Drawer): export Drawer element

### PR DESCRIPTION
**Pull request by araujobarret**
Related to #1295, I forgot to export the new element, this PR exports it.

### CODE REVIEW

**Comment by araujobarret** [comment]
Locally works the test works, only at the upper level with lerna it fails, investigating it (multirepo 😞 )

**Comment by araujobarret** [comment]
It was a mistake made be me, I introduced a circular dependency in the other PR. It's fixed now.

**Comment by artsyit** [comment]
:rocket: PR was released in [`@artsy/palette-charts@32.3.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette-charts%4032.3.0), [`@artsy/palette@33.3.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette%4033.3.0) :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in [`@artsy/palette-charts@36.0.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette-charts%4036.0.0), [`@artsy/palette@37.0.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette%4037.0.0) :rocket:

**Pull request merged**
