### PR TITLE
[storybook 6 upgrade]: Converts stories to CSF

### PR DESCRIPTION
**Pull request by dzucconi**
On a mission to get Storybook in some decent shape pending this Palette 3 move.

Firstly: moving our stories into CSF since this old `storiesOf` form is no longer supported. [Read about the format here](https://storybook.js.org/blog/component-story-format/)

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```sh
  npm install @artsy/palette@13.32.1-canary.853.14952.0
  # or 
  yarn add @artsy/palette@13.32.1-canary.853.14952.0
  ```
</details>

### CODE REVIEW

**Comment by dzucconi** [comment]
(The visual specs should be un-changed / have the same titles etc.)

**Comment by dzucconi** [comment]
Works locally but looks like it's not building properly for Chromatic; will peep that tomorrow.

**Comment by dzucconi** [comment]
One of the nice things here is that you can see how we could for instance use these stories in the palette website, since they are now portable, rather than have to write duplicate documentation.

**Review by damassi — APPROVED** [review]
Wow, this is wayyy better 👍 

(Would be worth having a larger separate convo about docs -- agree that the duplication isn't ideal and Storybooks supports jsx now.)

**Comment by dzucconi** [comment]
OK, for whatever reason `build-storybook` wasn't properly loading the stories. Went in and just upgraded to Storybook 6 which actually isn't so difficult because the config is so dramatically simplified (out of the box TypeScript!). I think I might have to update the Chromatic CLI stuff though; lessee.

**Comment by dzucconi** [comment]
TODO

- [ ] Unpend remaining `ModalBase` spec
- [ ] Figure out how to get visual-test to pass (baseline has changed; might be viewports plugin?)
- [ ] Rebase with master / convert Toggle.story

**Comment by dzucconi** [comment]
✅ ✅ ✅ ✅ ✅

**Comment by artsyit** [comment]
:rocket: PR was released in [`@artsy/palette@13.32.1`](https://github.com/artsy/palette/releases/tag/%40artsy/palette%4013.32.1) :rocket:

**Pull request merged**
