### PR TITLE
Moves luxon to dependency

### PR DESCRIPTION
**Pull request by kierangillen**
- Removes `luxon` as a peer and dev dependency and moves it to a dependency

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 199dc8ece7304377edc620596ddc4402d38c7a4a

https://deploy-preview-512--artsy-palette.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 604243c8f1f1c5a59a5c2e835803f158d978ed97

https://deploy-preview-512--artsy-palette.netlify.com

**Comment by anandaroop** [comment]
Thanks! 🙏

**Comment by artsyit** [comment]
:rocket: PR was released in v4.14.16 :rocket:

**Pull request merged**
