### PR TITLE
WIP => refactor(popover): New positioning engine 

### PR DESCRIPTION
**Pull request by damassi**
WIP

### CODE REVIEW

**Comment by dzucconi** [comment]
Keep in mind we'd want to refactor everything that uses `usePosition`

**Comment by damassi** [comment]
Right, yeah I just wanted to throw up something that (kinda) works to see what the crossover might be. I would imagine we'd simply replace usePosition internals with this to keep the same api, but this is more in your court. 

@dzucconi - Q: if this is a big project (and it seems like it is) would you be open to pulling down volt 2 and updating `Layout` to work as expected, where body scrolls instead of this wack inner div? I imagine that would be a 10m change for you, and that would push the necessity of this refactor out.

**Comment by dzucconi** [comment]
Yeah that sounds reasonable. Will take a look tomorrow AM

**Comment by damassi** [comment]
Thanks so much -- just be sure to boot volt 1 before starting volt 2, and everything should be good to dev in. (Can just push to my progressive onboarding branch, as the tooltips and so on are all ready to go) 👍 🙏

**Pull request closed without merging**
