### PR TITLE
Passes disabled to Slider

### PR DESCRIPTION
**Pull request by kierangillen**
- Passes `disabled` prop to Slider to update PriceRange filter color

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit a430e544f79c3cd1d735c6818bd60b15f6349caa

https://deploy-preview-462--artsy-palette.netlify.com

**Comment by damassi** [comment]
👍

**Comment by artsyit** [comment]
:rocket: PR was released in v4.11.8 :rocket:

**Comment by artsyit** [comment]
:rocket: PR was released in v4.11.8 :rocket:

**Pull request merged**
