### PR TITLE
Prototype a design system site

### PR DESCRIPTION
**Pull request by zephraph**
This is just a test using [docz](https://www.docz.site/) to generate a design system landing page. This isn't intended to be merged as is, more of an experiment to let us explore the possibility of having a design system site.  

image

It might not be worth keeping, but I thought it'd be cool for us to play around with. Let me know what you think. 

Here's a preview: https://dist-pylqxcidwa.now.sh/

### CODE REVIEW

**Comment by orta** [comment]
This is really nice and small, feels good to me TBH

**Comment by sweir27** [comment]
Yeah this is super nice. I didn't realize you could `Edit` right from the UI-- nice that it can be maintained by anyone.

**Comment by alloy** [comment]
Looking great @zephraph 👌

**Pull request merged**
