### PR TITLE
Update palette to allow clicking into the bars

### PR DESCRIPTION
**Pull request by lilyfromseattle**
Bar chart updated to accept an onClick that can open a url in a new tab

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 08ecc31f4a9f4a73b9b42ff147f0be623731d063

https://deploy-preview-373--artsy-palette.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 2c15a2fa83b9b1c69f382c4dd3bb30f587ce44a1

https://deploy-preview-373--artsy-palette.netlify.com

**Comment by sweir27** [comment]
Cool! 🎉

**Comment by artsyit** [comment]
:rocket: PR was released in v4.7.5 :rocket:

**Pull request merged**
