### PR TITLE
Initial issue template

### PR DESCRIPTION
**Pull request by zephraph**
This adds a spec addition/update issue template to palette

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit f0ca00cc1a076351b164b87f24c82da6e79b2183

https://deploy-preview-98--artsy-palette.netlify.com

**Comment by nicoleyeo** [comment]
@zephraph nice! (n00b question) Where's the best way for me to preview how this template actually displays on GH?

A few areas of detail to add for each component:

1. Guidelines
2. States/Options
3. Sizes

**Comment by nicoleyeo** [comment]
@jeffreytr once the checklists are done, would be great to add those to these templates !!!!!!!

**Pull request merged**
