### PR TITLE
Optimizing svgs

### PR DESCRIPTION
**Pull request by mdole**
Some of our SVGs in Palette are much larger than they need to be. I ran all of our SVGs through [SVGOMG](https://jakearchibald.github.io/svgomg/) to check sizes and then updated those that could be substantially optimized (I set an arbitrary cutoff of ~15% or 50 bytes).

Also chatted with @orta about implementing an SVG-optimizing script using a tool like [SVGO](https://github.com/svg/svgo), but realized that our situation is complicated somewhat because these aren't simple `.svg` files, they're `.tsx` files and many of them have React properties. Shelving that for now, but could be fun to look into in the future.

Tracked in [this ticket](https://artsyproduct.atlassian.net/browse/PLATFORM-1166)

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit c8893f1cf74795b17aab077e5e63d1c944744a77

https://deploy-preview-297--artsy-palette.netlify.com

**Comment by orta** [comment]
Sounds like you need to do some crazy AST parsing @mdole 

https://medium.com/@jotadeveloper/abstract-syntax-trees-on-javascript-534e33361fc7

**Comment by zephraph** [comment]
Yaaass! I love it. Thanks for this! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdole** [comment]
@orta hooooooboy

**Comment by artsyit** [comment]
:rocket: PR was released in v3.0.7 :rocket:

**Pull request merged**
