### PR TITLE
Add design and engineering checklists to issue template

### PR DESCRIPTION
**Pull request by anandaroop**
Per discussion in previous design system syncs — we want to provide ourselves with checklists to improve the quality of the components we are delivering, and to ease the cognitive burden of remembering all the things.

To that end, @jeffreytr and I worked up one design- and one engineering-focused checklist to add to the issue template. 

These are not meant to be exhaustive, nor to serve as blockers for any particular PR. Rather they are intended to visibly signpost common goals and to help us be on the same page. If this or that item on the checklist doesn't feel right we should definitely feel free to iterate on these.

screen shot 2018-11-07 at 10 33 16 am

screen shot 2018-11-07 at 10 33 27 am

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 904647d308ba98c586e08a3f1f4e0c7f22a27ee7

https://deploy-preview-123--artsy-palette.netlify.com

**Comment by alloy** [comment]
Love it! The only thing that I think could do with some clarification is the “artsy supported browsers”. I’m not sure if the compatibility list at the bottom was meant, but it would be good to have a list of browsers/versions. Do we have a definitive list by now and, if so, can you link to it?

**Comment by zephraph** [comment]
@alloy brings up a good point. Let's do that in a follow up though. Great job!

**Comment by anandaroop** [comment]
Thanks for merging, I agree those are good questions. There are a couple of other areas that could be less ambiguous too, e.g. "`aria` attributes where appropriate". Let's keep refining these.

**Pull request merged**
