### PR TITLE
[PURCHASE-1577] Tag component

### PR DESCRIPTION
**Pull request by sepans**
[PURCHASE-1577](https://artsyproduct.atlassian.net/browse/PURCHASE-1577)

[Design](https://app.zeplin.io/project/5acd19ff49a1429169c3128b/screen/5d96541467c03315a0266529)

TODO:
- [x] Fix mdx file

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 365609115d062944d34ccdbeb68e152dcf434987

https://deploy-preview-608--artsy-palette.netlify.com

**Comment by samchieng** [comment]
@sepans ooooo yes! i think the only thing missing is there should be a `2px` border-radius for both tags

**Comment by sepans** [comment]
🙏 thanks @samchieng totally missed that.

**Comment by zephraph** [comment]
This is 👍. 

A thought for the future: should there be a default limit on the number of tags to display?

I think we can merge without that today though.

**Comment by artsyit** [comment]
:rocket: PR was released in v5.1.0 :rocket:

**Comment by samchieng** [comment]
@zephraph prob depends on the context, but i can't imagine a situation where we'd ever show more than up to 8 by default, so if its helpful we can use this number for now.

Just thinking on the Artwork page, we'll probably only get 6 max

**Pull request merged**
