### PR TITLE
Remove separator from pagination component

### PR DESCRIPTION
**Pull request by iskounen**
When I migrated `LargePagination` from Reaction to Palette, I brought with it a separator component that is used in Force but not in Volt. I have [put the separator component back in Reaction](https://github.com/artsy/reaction/pull/1954) and removed it from Palette so that it doesn't become a part of the shared component library.

### CODE REVIEW

**Comment by damassi** [comment]
👍

**Comment by damassi** [comment]
merge on green

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 5b0ed40cf0f108b002a87798d2c0af08c5f3f423

https://deploy-preview-236--artsy-palette.netlify.com

**Comment by artsyit** [comment]
:rocket: PR was released in v2.36.0 :rocket:

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 87a0a29ca72372967adc0e388547acff8f6251bd

https://deploy-preview-236--artsy-palette.netlify.com

**Pull request merged**
