### PR TITLE
PURCHASE-1361 Fixes button breaking viewport

### PR DESCRIPTION
**Pull request by kierangillen**
- Fixes Buttons breaking the width of their container based on the hardcoded width. Now computes width from the view width.

## After fix

Screen Shot 2019-07-25 at 1 20 43 PM

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit eadad78d3c3d73bc05da78a229c83c4b383fe467

https://deploy-preview-546--artsy-palette.netlify.com

**Comment by ds300** [comment]
As mentioned in person, I found a way to fix this which removes some code and allows the component to be variable-width, but I don't quite understand why it works. You think it's worth investigating, @kierangillen ? I'd want to check that it works in other contexts and on various devices.

**Comment by kierangillen** [comment]
#mergeongreen

**Comment by artsyit** [comment]
:rocket: PR was released in v4.14.39 :rocket:

**Pull request merged**
