### PR TITLE
feat(radio): supports generic type

### PR DESCRIPTION
**Pull request by dzucconi**
Closes [DIA-729](https://artsyproduct.atlassian.net/browse/DIA-729)

Re: https://artsy.slack.com/archives/C2TQ4PT8R/p1718623491874389

[DIA-729]: https://artsyproduct.atlassian.net/browse/DIA-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dariakoko — APPROVED** [review]
Thank you!

**Comment by dzucconi** [comment]
Just a note though: this can't infer the type from the child radios when you're using `RadioGroup` — it'll infer based on the `defaultValue`. If you want to specify a mixed type then you'll have to provide it like: `<RadioGroup<string | boolean> ...`

**Comment by artsyit** [comment]
:rocket: PR was released in [`@artsy/palette-charts@37.13.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette-charts%4037.13.0), [`@artsy/palette@38.13.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette%4038.13.0) :rocket:

**Comment by dariakoko** [comment]
@dzucconi thanks for the fix. I have an issue setting the default value to false. Do you have any idea why it can be?
The `selected` prop value always stays `false` when the initial value is false
image

**Pull request merged**
