### PR TITLE
Address Design QA

### PR DESCRIPTION
**Pull request by damassi**
Finishes up this list: https://github.com/artsy/palette/issues/279

@zephraph - i turned off the editorial flow for now. That thing is kinda whatevs for something like this where minor edits are often all that's needed. Let me know if you feel strongly about it.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 8367f1fda4e7d32b0035c7264b49f49b9b18a826

https://deploy-preview-280--artsy-palette.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 3d1f74ebad12eaa7022574f10bffe7f097805079

https://deploy-preview-280--artsy-palette.netlify.com

**Comment by artsyit** [comment]
:rocket: PR was released in v2.37.21 :rocket:

**Comment by zephraph** [comment]
Sorry, I missed this PR. 

I'm fairly indifferent about the workflow itself, but without it there's a release for every doc change. Ultimately that should be fixed in auto, but until then I'm not sure that we should disable it.

**Pull request merged**
