### PR TITLE
GRO-836: Adding design update for gallery attributes, until further approval on designs met

### PR DESCRIPTION
**Pull request by The-Beez-Kneez**
Screen Shot 2022-03-30 at 11 50 35 AM

### CODE REVIEW

**Review by dzucconi — COMMENTED** [review]
Rather: let's just get rid of the variants all together

**Comment by The-Beez-Kneez** [comment]
Would prefer to leave them for now, as this is an ongoing design discussion. They keep going back and forth on it, and have yet to reach a solid design to represent a multi attribute scenario.

**Comment by dzucconi** [comment]
You could just remove the keys for the other variants and leave the default variant then, since nothing is using them.

**Comment by The-Beez-Kneez** [comment]
But if we receive details in the next few weeks for varied styling of multiple attributes, we can just use the code here.

The plan is to support multiple of these, I think it best the logic is there so we do not have to put it back in when we end up with 3 Gallery Attribute categories.

**Comment by dzucconi** [comment]
I disagree — there's no value in having placeholder code. It's not hard to add real variants when we want to. We probably wouldn't even name them this.

I'd leave the `default` variant alone and just remove the other keys.

**Comment by dzucconi** [comment]
(I'm not stressing about it either way though. If you feel strongly just approve the UI tests and merge.)

**Comment by artsyit** [comment]
:rocket: PR was released in [`@artsy/palette-charts@18.2.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette-charts%4018.2.0), [`@artsy/palette@19.2.0`](https://github.com/artsy/palette/releases/tag/%40artsy/palette%4019.2.0) :rocket:

**Pull request merged**
