### PR TITLE
Update to styled-system v5

### PR DESCRIPTION
**Pull request by zephraph**
Much like the styled-components upgrade, a styled systems upgrade promises higher performance (with less prop noise). This is obviously a _major_ update and we'll  want to use the canary across a few different consumers just to ensure we don't break things. 

## Components Updated

- [ ] Avatar
- [ ] Banner
- [ ] BarChart
- [ ] BorderBox
- [x] Box
- [x] Button
- [x] Flex
- [ ] Checkbox
- [x] CleanTag
- [ ] Collapse
- [ ] Colors
- [x] CSSGrid
- [ ] DataVis
- [ ] Dialog
- [ ] DonutChart
- [ ] EntityHeader
- [ ] Grid
- [x] Image
- [ ] Input
- [ ] Join
- [ ] LabeledRange
- [ ] LineChart
- [ ] Link
- [ ] Menu
- [ ] Message
- [ ] Modal
- [ ] Pagination
- [ ] PriceRange
- [ ] ProgressBar
- [ ] ProgressBarTimer
- [ ] Radio
- [ ] RadioGroup
- [ ] ReadMore
- [ ] Select
- [ ] Separator
- [ ] Slider
- [ ] Spacer
- [ ] Spinner
- [ ] StackableBorderBox
- [ ] StaticCountdownTimer
- [ ] Stepper
- [ ] Tabs
- [ ] Tags
- [ ] TextArea
- [ ] TimeRemaining
- [ ] Toggle
- [ ] Tooltip
- [x] Typography

<details>
  <summary>📦 Published PR as canary version: <code>9.0.0-canary.667.10289.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```sh
  npm install @artsy/palette@9.0.0-canary.667.10289.0
  # or 
  yarn add @artsy/palette@9.0.0-canary.667.10289.0
  ```
</details>

### CODE REVIEW

**Comment by damassi** [comment]
@zephraph - I tried this last year some time and noticed that all of our spacing blew up on the reaction / force side and didn't have a proper path forward (styled-system no longer assumes px, or something?). Would recommend linking there sooner rather than later. (Also [heres a branch](https://github.com/artsy/palette/compare/upgrade-styled-system-v5?expand=1) where i was working if it might be of any help.)

**Comment by zephraph** [comment]
Yep, I read that as well. Does seem like it's going to be a significant challenge, but we can't keep sitting on these upgrades. Gotta rip off that bandaid sometime.

**Comment by damassi** [comment]
Once you get to a point of confidence happy to help out in any way I can.

**Comment by zephraph** [comment]
My aim is to get a canary released and integrated in a few consuming repos so we can start digging in more from there.

**Comment by zephraph** [comment]
@ds300 or @damassi there's a TS error coming from some components whose props extend from `FlexProps` (our components props, not those from styled-system). 

I'm not sure exactly what's causing this or why. If either of you could poke it I'd appreciate it! 🙏

**Comment by damassi** [comment]
@zephraph - if you cast the return value of the [`color` helper](https://github.com/artsy/palette/blob/master/packages/palette/src/helpers/color.ts) as a string i bet it will fix all of the type errors.

**Comment by zephraph** [comment]
Yeah, you're probably right. I don't necessarily want that to be a string though, it's really useful having color suggest supported values... 

Hmmm...

**Pull request closed without merging**
