### PR TITLE
Removes moment and moment-timezone

### PR DESCRIPTION
**Pull request by kierangillen**
- Removes `moment` and `moment-timezone` and uses `luxon` as a replacement
- This PR is the first step in removing `moment` from Reaction and Palette as decided in this issue https://github.com/artsy/reaction/issues/2474

## After changes

Screen Shot 2019-06-06 at 12 26 07 PM

Screen Shot 2019-06-06 at 12 25 58 PM

Screen Shot 2019-06-06 at 12 27 20 PM

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-palette* ready!

Built with commit 45b92e5accec064151e80d179bcb031804a7513a

https://deploy-preview-499--artsy-palette.netlify.com

**Comment by damassi** [comment]
@kierangillen - Justin is OOO, but this looks good 👍

**Comment by artsyit** [comment]
:rocket: PR was released in v4.14.5 :rocket:

**Comment by alloy** [comment]
Nice one, @kierangillen

**Comment by damassi** [comment]
@kierangillen - I know we spoke about those weird snapshot failures in Reaction but I'm gonna revert this in the meantime so that deploys aren't blocked. We can unrevert tomorrow.

**Comment by damassi** [comment]
https://github.com/artsy/palette/pull/504

**Pull request merged**
